# Setup
title:            Sisune <3 Gamma for help
tagline:          'He is a great friend'
description:      'A brazen two-column <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://sisune.github.io/gh-pages-custom/
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Sisune Moe'
  url:            https://twitter.com/Sisune_moe

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
